name: Compiling
on: workflow_dispatch
jobs:
  Android:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        build: [debug, release]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4

      - name: Installing Libraries
        run: haxelib install hmm && haxelib run hmm install

      - name: Setup Git hxcpp
        run: haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp.git --quiet && haxelib run lime rebuild hxcpp

      - name: List of installed Haxe Libraries
        run: haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Building
        run: haxelib run lime build android -${{matrix.build}}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: androidBuild-${{matrix.build}}
          path: export/android/bin/app/build/outputs/apk/debug
          if-no-files-found: warn
